### PR TITLE
Master

### PR DESCRIPTION
**Pull request by tallzilla**
Hi there - I’m a husband of a (former) gawker editor and found your script. Handy!

I made a few tweaks and built out the readme, so that (hopefully!) non-technical folks can get the script running without having to edit it manually or install dependencies.

I also incorporated the 50-char line indentation bug found by @abayer 

Merge this sucker!

### CODE REVIEW

**Comment by Srol** [comment]
Hey cool. I'll give this a test tomorrow and merge if it's all clear. Thanks for doing all the work I was too lazy to.

**Comment by tallzilla** [comment]
Thanks @Srol. There may be some urgency behind the fix (especially @abayer's issue). As you know gawker's shutting down, there's at least one thread amongst gawker alumni that involves folks running your script to save posts before they disappear.

Hope the tests work!

**Comment by abayer** [comment]
@tallzilla ...ok, the world is officially very small. =)

**Comment by tallzilla** [comment]
@abayer Haah I should have figured that out.

@Srol Save us! Also, hope you aren't related to Hulk Hogan ;)

**Comment by Srol** [comment]
No relation. 

Test went well once I'd realized you switched it from Python 3 to 2. I've been trying to force myself to work with 3 lately, but if journalists unfamiliar with the command prompt are gonna be running this, the version that comes with OS X is probably a better choice, good call. Merging now.

**Comment by tallzilla** [comment]
<3

**Pull request merged**
